<?php

/**
 * @var \HWW\MenuCreate\Block\Frontend\CategoryItem $block
 */
$items = $block->getItems();
$category = $block->getCategory();
$filtered_items = $block->getFilteredItems();
$countItems = count($filtered_items);

?>

<div class="count_items_ajax">
    <p>There are currently <?php echo $countItems ?> names in this directory</p>
</div>

<?php if (count($filtered_items)) { ?>
    <div class="items">
        <?php
        foreach ($filtered_items as $filtered_item) {
            echo '<div id="title-id" catagory-name=' . $filtered_item->getCategoryName() . ' class="item-id ' . strtolower(str_replace(' ', '_', $filtered_item->getCategoryName())) . '">
                <h4 class="title" >' . $filtered_item->getTitle() . '</h4>
                <p class="description">' . $filtered_item->getDescription() . '</p>
                </div>';
        }
        ?>
    </div>
<?php
}
?>