<?php

/**
 * @var \HWW\MenuCreate\Block\Frontend\Display $block
 */
$items = $block->getItems();
$category = $block->getCategory();
?>
<?php $total_count = count($category); ?>
<?php if (count($category)) { ?>
    <div class="category">
        <?php echo "View:" ?>
        <?php $set_count = 0; ?>
        <?php foreach ($category as $content) { ?>
            <?php $set_count += 1; ?>
            <?php $categoryName = $content->getCategoryName(); ?>
            <a class="<?php echo strtolower(str_replace(' ', '_', $categoryName)) ?>" href="<?php echo $this->getUrl('menucreate/frontend/display'); ?>">
                <?php
                if ($set_count < $total_count) {
                    $categoryName = $categoryName . ",";
                    echo $categoryName;
                } else {
                    echo $categoryName;
                }
                ?>
            </a>
        <?php
        }
        ?>
    </div>
<?php
}
?>



<div class="search-bar" style="width: 300px">
    <div class="search-text">
        <input id="search-id" type="text" placeholder="Search for..." />
    </div>
    <input class="search-button" type="button" value="Search" />
</div>

<div class="default-items">
    <?php
    foreach ($items as $item) {
        if ($item->getCategoryName() == 'Glossary') {
            echo '<div class="item-id">
                <h4 class="title" >' . $item->getTitle() . '</h4>
                <p class="description">' . $item->getDescription() . '</p>
                </div>';
        }
    }
    ?>
</div>

<div class="ajax-content">
</div>

<script>
    require(['jquery', 'domReady!'], function($) {
        $('.category a').on('click', function(e) {
            e.preventDefault();
            $('.default-items').remove();
            $('.ajax-content .items').remove();
            let href = $(this).attr("class");
            // console.log(href);

            var template = 'categoryitem.phtml';
            console.log(href);
            $.ajax({
                type: "POST",
                url: "<?= $block->getBaseUrl(); ?>menucreate/frontend/categoryitem",
                data: {
                    category: href,
                },
                success: function(data) {
                    if (data != '') {
                        $('.ajax-content').append(data.output);
                    } else {
                        contentLocation.html("No Data");
                    }
                    console.log(data.output);
                    console.log("success!");
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    console.log('Error happens. Try again.');
                }
            });
        });

        $('.search-button').click(function(e) {
            e.preventDefault();
            $(".highlight").remove();

            var searchword = $("#search-id").val();

            var custfilter = new RegExp(searchword, "ig");
            var repstr = "<span class='highlight'>" + searchword + "</span>";

            if (searchword != "") {
                $('body').each(function() {
                    $(this).html($(this).html().replace(custfilter, repstr));
                })
            }

            var page = $('.item-id');
            page.each(function(index, element) {
                let text = $(this).text();
                let result = custfilter.test(text);
                if (result) {
                    $(this).css('display', 'block');
                } else {
                    $(this).css('display', 'none');
                }
            });
            
        });
    });
</script>