<?php
/**
 * @var \HWW\MenuCreate\Block\Frontend\Display $block
 */
$items = $block->getItems();
$category = $block->getCategory();
?>
<?php $total_count = count($category); ?>
<?php if (count($category)) { ?>
    <div class="category">
        <?php echo "View:" ?>
        <?php $set_count = 0; ?>
        <?php foreach ($category as $content) { ?>
            <?php $set_count += 1; ?>
            <?php $categoryName = $content->getCategoryName(); ?>
            <a class="<?php echo strtolower(str_replace(' ', '_', $categoryName)) ?>" href="<?php echo $this->getUrl('menucreate/frontend/display'); ?>">
                <?php
                if ($set_count < $total_count) {
                    $categoryName = $categoryName . ",";
                    echo $categoryName;
                } else {
                    echo $categoryName;
                }
                ?>
            </a>
        <?php
        }
        ?>
    </div>
<?php
}
?>

<div class="search-bar" style="width: 300px">
    <div class="search-text">
        <input id="search-id" type="text" placeholder="Search for..." />
    </div>
    <input class="search-button" type="button" value="Search" />
</div>

<div class="ajax-content">
</div>

<script>
    require(['jquery', 'domReady!'], function($) {
        function ajaxload() {
            var target = $(this);
            // var categoryName = target.attr('category-name');
            var template = 'categoryitem.phtml';
            $.ajax({
                type: "POST",
                url: "<?= $block->getBaseUrl(); ?>menucreate/frontend/categoryitem",
                data: {
                    // id: categoryName,
                    template: template
                },
                success: function(data) {
                    if (data != '') {
                        $('.ajax-content').append(data.output);
                    } else {
                        contentLocation.html("No Data");
                    }
                    console.log(data.output);
                    console.log("success!");
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    console.log('Error happens. Try again.');
                }
            });
        }

        $(document).ready(function() {
            ajaxload();
        });

        $('.category a').on('click', function(e) {
            e.preventDefault();
            let href = $(this).attr("class");
            console.log(href);
            $(".ajax-content .items div").addClass('hidden');
            $(".ajax-content .items ." + href).removeClass('hidden');
        });

        $('.search-button').click(function(e) {
            e.preventDefault();
            var page = $('.item-id');
            var pageText = page.text().replace("<span>", "").replace("</span>");
            var searchedText = $('#search-id').val();
            var theRegEx = new RegExp("(" + searchedText + ")", "igm");
            var newHtml = pageText.replace(theRegEx, "<span>$1</span>");
            //$(".ajax-content .items span").css('background-color',"yellow");
            console.log(newHtml);
            page.each(function(index, element) {
                let text = $(this).text();
                let result = theRegEx.test(text);
                if (result) {
                    $(this).css('display', 'block');
                } else {
                    $(this).css('display', 'none');
                }
            });
        });
    });
</script>